server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oxygen
    password: franklin
    username: root

  redis:
    port: 6379
    host: localhost
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 3

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
