# 开发环境配置
server:

  port: 8080  #8686 #8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oxygen
    password: franklin
    username: root

  redis:
    port: 6379
    host: localhost
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 3

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
